// Generated by CoffeeScript 1.6.2
(function() {
  var Track;

  exports.parse = function(pls) {
    var i, line, lines, match, numberOfEntries, obj, track, tracks, _i, _j, _len;

    obj = {};
    tracks = [];
    lines = pls.split("\n");
    for (_i = 0, _len = lines.length; _i < _len; _i++) {
      line = lines[_i];
      match = line.match(/([a-zA-Z0-9]+)\=(.+)$/);
      if (match && match.length >= 2) {
        obj[match[1].toLowerCase()] = match[2];
      }
    }
    numberOfEntries = parseInt(obj.numberofentries, 10) || 0;
    for (i = _j = 1; _j <= numberOfEntries; i = _j += 1) {
      track = new Track(obj["file" + i], obj["title" + i], parseInt(obj["length" + i], 10));
      tracks.push(track);
    }
    return tracks;
  };

  Track = function(uri, title, length) {
    this.uri = uri;
    this.title = title;
    this.length = length;
    return this;
  };

}).call(this);
